/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exceltest;

import java.awt.event.KeyEvent;
import java.util.ArrayList;

/**
 *
 * @author Vince
 */
public class caseProdFrame extends javax.swing.JFrame {

    /**
     * Creates new form caseProdFrame
     */
    private ArrayList<String> caseListArray;
    
    
    public caseProdFrame() {
        
        caseListArray = new ArrayList<String>();
        
        initComponents();
        
        updateProdInfo(caseList.getItemCount());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        caseTextField = new javax.swing.JTextField();
        caseList = new java.awt.List();
        jScrollPane1 = new javax.swing.JScrollPane();
        productionInfo = new javax.swing.JTextArea();
        caseProductionLabel = new javax.swing.JLabel();
        caseLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel1.setBackground(new java.awt.Color(204, 204, 204));

        caseTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caseTextFieldActionPerformed(evt);
            }
        });
        caseTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                caseTextFieldKeyPressed(evt);
            }
        });

        productionInfo.setEditable(false);
        productionInfo.setColumns(10);
        productionInfo.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        productionInfo.setRows(5);
        jScrollPane1.setViewportView(productionInfo);

        caseProductionLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        caseProductionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        caseProductionLabel.setText("Case Production Tool");

        caseLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        caseLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        caseLabel.setText("Case");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(caseProductionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(caseLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(caseTextField)
                            .addComponent(caseList, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 10, Short.MAX_VALUE))))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(caseProductionLabel)
                .addGap(34, 34, 34)
                .addComponent(caseLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(caseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(caseList, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(168, Short.MAX_VALUE))))
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void updateProdInfo(int count){
        
        int prodGoal = 500;
        int avgHr = 0;
        
        productionInfo.setText("Case Count: "+ count + "\n" +
                               "Avg/Hour: " + avgHr + "\n" +
                               "Daily Goal: " + prodGoal);
    }
    private void caseTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caseTextFieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_caseTextFieldActionPerformed

    private void caseTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caseTextFieldKeyPressed
        // TODO add your handling code here:
        int keyCode = evt.getKeyCode();
        String caseID = caseTextField.getText();
        
        if(keyCode == KeyEvent.VK_ENTER){
            if(caseID.length()!=0){
                if(!caseID.contains(" ")){
                    if(!caseListArray.contains(caseID)){
                        caseListArray.add(caseID);
                        caseList.add(caseID);
                        caseTextField.setText("");
                        updateProdInfo(caseList.getItemCount());
                    }
                }else{
                    System.out.println("Empty");
                }
                
            }else{
                System.out.println("Null");
            }
            
            
        }
        
    }//GEN-LAST:event_caseTextFieldKeyPressed

    public void run(){
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new caseProdFrame().setVisible(true);
            }
        });
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(caseProdFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(caseProdFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(caseProdFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(caseProdFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel caseLabel;
    private java.awt.List caseList;
    private javax.swing.JLabel caseProductionLabel;
    private javax.swing.JTextField caseTextField;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Panel panel1;
    private javax.swing.JTextArea productionInfo;
    // End of variables declaration//GEN-END:variables
}
