/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exceltest;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;


/**
 *
 * @author Vince
 */


public class DatabaseFrame extends javax.swing.JFrame {

    private String selectionType;
    private String date;
    private String area;
    private String shift;
    private ArrayList<String> areaListArray;
    private TableModel tbModel; 
    private TableModel prodModel; 
    private Object[] tbColumn;
    private Object[] prodColumn;
    /**
     * Creates new form DatabaseFrame
     */
    public DatabaseFrame() {
        
        tbModel = new DefaultTableModel();
        prodModel = new DefaultTableModel();
        selectionType = new String();
        date = new String();
        area = new String();
        shift = new String();
        areaListArray = new ArrayList<String>();
        areaListArray = DatabaseObj.getAreaList();
        if(!areaListArray.contains("All")){
            areaListArray.add("All");
        }

        initComponents();
        initialize();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        typeComboBox = new javax.swing.JComboBox<>();
        dateLabel = new javax.swing.JLabel();
        entryProdTab = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        theTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        prodTable = new javax.swing.JTable();
        typeLabel = new javax.swing.JLabel();
        areaLabel = new javax.swing.JLabel();
        shiftLabel = new javax.swing.JLabel();
        areaComboBox = new javax.swing.JComboBox<>();
        shiftComboBox = new javax.swing.JComboBox<>();
        queryButton = new javax.swing.JButton();
        dateTextField = new javax.swing.JFormattedTextField();
        statusLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        typeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cell Records", "Tech Records", "Attendance Records" }));
        typeComboBox.setSelectedItem(" ");
        typeComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                typeComboBoxItemStateChanged(evt);
            }
        });

        dateLabel.setText("Date");

        theTable.setModel(tbModel);
        theTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane1.setViewportView(theTable);

        entryProdTab.addTab("Entries", jScrollPane1);

        prodTable.setModel(prodModel);
        jScrollPane2.setViewportView(prodTable);

        entryProdTab.addTab("Entry Prod", jScrollPane2);

        typeLabel.setText("Type");

        areaLabel.setText("Area");

        shiftLabel.setText("Shift");

        areaComboBox.setModel(new DefaultComboBoxModel(areaListArray.toArray()));
        areaComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                areaComboBoxItemStateChanged(evt);
            }
        });

        shiftComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "All" }));

        queryButton.setText("Query");
        queryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                queryButtonActionPerformed(evt);
            }
        });

        dateTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("M/d/yyyy"))));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(typeLabel)
                            .addComponent(dateLabel)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(dateTextField)
                                .addComponent(typeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(areaLabel)
                                        .addGap(107, 107, 107))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(areaComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(7, 7, 7)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(shiftLabel)
                                    .addComponent(shiftComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(queryButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(entryProdTab, javax.swing.GroupLayout.PREFERRED_SIZE, 744, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(entryProdTab, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(typeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(typeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(dateLabel)
                        .addGap(8, 8, 8)
                        .addComponent(dateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(areaLabel)
                            .addComponent(shiftLabel))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(areaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(shiftComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(220, 220, 220)
                        .addComponent(queryButton)))
                .addContainerGap())
        );

        mainPanel.addTab("Query", jPanel1);

        statusLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        statusLabel.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addComponent(statusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(statusLabel)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void initialize(){
        
        statusLabel.setText(DatabaseObj.getStatus());
        
        theTable.getTableHeader().setReorderingAllowed(false);
        theTable.getTableHeader().setResizingAllowed(false);
        theTable.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
            public void valueChanged(ListSelectionEvent event) {
            
                if(theTable.getSelectedRow()!=-1){
                    if(theTable.getValueAt(theTable.getSelectedRow(), 0)!= null){

                        try{

                            Object[][] ob = makeProdObjectFromArray(DatabaseObj.executeGetTechProdRecordsQ((int)theTable.getValueAt(theTable.getSelectedRow(), 0)));
                            prodModel = new DefaultTableModel(ob,prodColumn);
                            prodTable.setModel(prodModel);
                        }catch(Exception e){
                            System.out.println(e.toString());
                        }
                    }
                }     
            }
        });
        
        tbColumn = new Object[]{"ID","Date","Area","Shift","Total Comp","Net Goal Total","% of Goal","% of Fails"};
        prodColumn = new Object[]{"TechID","FName","LName","iPhone","iPad","iTouch","Classic","Shuffle","Nano","A.Phone","A.Tab","Wearables","Total"};
        tbModel = new DefaultTableModel(tbColumn,10);
        theTable.setModel(tbModel);
        
    }
    
    private Object[][] makeObjectFromArray(ArrayList<ArrayList> ar){
        
        if(ar.size()==0){
            JOptionPane.showMessageDialog(this,"No Entry For This Criteria","Try Again", JOptionPane.WARNING_MESSAGE);
        }
        Object[][] ob = new Object[ar.size()][tbColumn.length];
        
        for(int row = 0;row<ar.size();row++){
            for(int col =0;col<tbColumn.length;col++){
                
                ob[row][col] = ar.get(row).get(col);  
            }
        }
        
        return ob;
    }
    
    private Object[][] makeProdObjectFromArray(ArrayList<ArrayList> ar){
        
        if(ar.size()==0){
            JOptionPane.showMessageDialog(this,"No Entry For This Criteria","Try Again", JOptionPane.WARNING_MESSAGE);
        }
        
        Object[][] ob = new Object[ar.size()+1][prodColumn.length];
        
        for(int row = 0;row<ar.size()+1;row++){
            for(int col =0;col<prodColumn.length;col++){
                
                ob[row][col] = 0;  
            }
        }
        
        for(int row = 0;row<ar.size();row++){
            for(int col =0;col<prodColumn.length;col++){
                
                ob[row][col] = ar.get(row).get(col);
                
                if(col ==0){
                    ob[ar.size()][col] = "Totals";
                }else if(col > 2){
                    if(row<ar.size()){
                        ob[ar.size()][col] = (int)ob[row][col]+(int)ob[ar.size()][col];
                    }   
                }else{
                    ob[ar.size()][col] = " ";
                }    
            }
        }
        
        return ob;
    }
     
    private void queryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_queryButtonActionPerformed
        // TODO add your handling code here:
        selectionType = (String)typeComboBox.getSelectedItem();
        date = dateTextField.getText();
        area = (String)areaComboBox.getSelectedItem();
        shift = (String)shiftComboBox.getSelectedItem();
        
        try{
          
            switch(selectionType){
                case "Cell Records":
                    if(!date.equals("")){
                        Object[][] ob = makeObjectFromArray(DatabaseObj.executeGetCellRecordsQ(date, area, shift));
                        tbModel = new DefaultTableModel(ob,tbColumn);
                        theTable.setModel(tbModel); 
                    
                    }else{
                        JOptionPane.showMessageDialog(this,"Date Must Be Entered","Try Again", JOptionPane.WARNING_MESSAGE);
                    }
                    
                    break;

            }
            
            
        }catch(Exception e){
            System.out.println(e.toString());
        }
        
    }//GEN-LAST:event_queryButtonActionPerformed

    private void areaComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_areaComboBoxItemStateChanged
        // TODO add your handling code here:
        if((String)areaComboBox.getSelectedItem() == "All"){
            shiftComboBox.setEnabled(false);
        }else{
            shiftComboBox.setEnabled(true);
        }
    }//GEN-LAST:event_areaComboBoxItemStateChanged

    private void typeComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_typeComboBoxItemStateChanged
        // TODO add your handling code here:
        switch((String)typeComboBox.getSelectedItem()){
            case "Cell Records":
                
                tbColumn = new Object[]{"ID","Date","Area","Shift","Total Comp","Net Goal Total","% of Goal","% of Fails"};
                tbModel = new DefaultTableModel(tbColumn,10);
                theTable.setModel(tbModel);
                break;
            case "Tech Records":
                
                Object[] col = {"one","two","three"};
                tbModel = new DefaultTableModel(col,10);
                theTable.setModel(tbModel);
                break;
            case "Attendance":
                break;
        }
    }//GEN-LAST:event_typeComboBoxItemStateChanged

    /**
     * @param args the command line arguments
     */
    
   
    
    public void run(){
           /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DatabaseFrame().setVisible(true);
            }
        }); 

    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DatabaseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DatabaseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatabaseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatabaseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> areaComboBox;
    private javax.swing.JLabel areaLabel;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JFormattedTextField dateTextField;
    private javax.swing.JTabbedPane entryProdTab;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane mainPanel;
    private javax.swing.JTable prodTable;
    private javax.swing.JButton queryButton;
    private javax.swing.JComboBox<String> shiftComboBox;
    private javax.swing.JLabel shiftLabel;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JTable theTable;
    private javax.swing.JComboBox<String> typeComboBox;
    private javax.swing.JLabel typeLabel;
    // End of variables declaration//GEN-END:variables
}
